### PR TITLE
58 mobile layout

### PR DESCRIPTION
**Pull request by michaelKurowski**
Desktop fixes:
- Added social media links on edit-profile desktop
- fixed article view header on desktop

Mobile:
- [x] articles view
- [x] articles listing / homepage
- [x] categories listing
- [x] authors
- [x] author profile
- [x] edit profile
- [x] register
- [x] login
- [x] error page
- [x] header
- [x] footer

### CODE REVIEW

**Comment by michaelKurowski** [comment]
todo: Convert top stories to slider on mobile

**Comment by michaelKurowski** [comment]
@Jordan141 Go ahead. Check them on mobile.

**Review by Jordan141 — CHANGES_REQUESTED** [review]
- [x] Article View
- [x]  Article Listing: Article titles are black instead of the primary purple.
- [x] Category listing
- [x] Authors, too black and white, refer to previous colour palette
- [ ] Author profile, same as above
- [x] Edit Profile
- [ ] Register, should we have newsletter on the bottom of our login/register forms?
- [ ] Login, same as above
- [x] Error page

Error:  Header styling is broken in mobile format
image

**Comment by michaelKurowski** [comment]
> Error: Header styling is broken in mobile format
This is what happens when you start in desktop view and then switch to mobile. 
Please refresh the page.

**Comment by michaelKurowski** [comment]
>  Register, should we have newsletter on the bottom of our login/register forms?
It's just that footer is always the same, I'm not sure we should break design.

**Comment by michaelKurowski** [comment]
@Jordan141 I've applied fixes to things you've mentioned.
Let me know if you'll spot anything else. Consider this PR to be the final design implementation. Both desktop and mobile.

**Review by Jordan141 — APPROVED** [review]

**Pull request merged**
