### PR TITLE
Devops

### LINKED ISSUE #21: Redis
Implement Redis DB Cache system for the project.

To be used in multiple areas, namely security and logging.

### PR DESCRIPTION
**Pull request by Jordan141**
This PR will focus on the following issues:

- [x] Restart the application on crash/failure if possible.
- [x] Dockerizing the application.
- [x] Installing and utilising Redis in the Docker application.
- [x] Installing and utilising MongoDB in the Docker application.
- [x] Setting up a docker-compose environment.
- ~~Finding a way to automatically rebuild the docker image on a script change.~~

Resolves #21, #15, #11,

### CODE REVIEW

**Comment by michaelKurowski** [comment]
What does redis do?

**Comment by michaelKurowski** [comment]
```
mkurowski:~/OSS/articleblog$ docker-compose up
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
mkurowski:~/OSS/articleblog$ docker-compose -v
docker-compose version 1.17.1, build unknown
mkurowski@mkurowski-Latitude-5480:~/OSS/articleblog$ apt-get install docker-compose
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
mkurowski@mkurowski-Latitude-5480:~/OSS/articleblog$ sudo apt-get install docker-compose
[sudo] password for mkurowski: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker-compose is already the newest version (1.17.1-2).
0 upgraded, 0 newly installed, 0 to remove and 177 not upgraded.
mkurowski:~/OSS/articleblog$ 

```

**Comment by michaelKurowski** [comment]
Changing version of dockerfile to 3.3 and name of `DockerFile` to `Dockerfile` helped. Please apply these changes

**Comment by michaelKurowski** [comment]
Mongo ends up in restart loop
```
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.302+00:00"},"s":"W",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****","tags":["startupWarnings"]}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.309+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.325+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.326+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.328+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":27,"port":27017,"dbPath":"/var/lib/mongodb","architecture":"64-bit","host":"d9a0e72377e5"}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.328+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.1","gitVersion":"ad91a93a5a31e175f5cbf8c69561e788bbc55ce1","openSSLVersion":"OpenSSL 1.1.1  11 Sep 2018","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu1804","distarch":"x86_64","target_arch":"x86_64"}}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.329+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"18.04"}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.329+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/tmp/docker-entrypoint-temp-config.json","net":{"bindIp":"127.0.0.1","port":27017,"tls":{"mode":"disabled"}},"processManagement":{"fork":true,"pidFilePath":"/tmp/docker-entrypoint-temp-mongod.pid"},"storage":{"dbPath":"/var/lib/mongodb","journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"path":"/proc/1/fd/1"}}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"IllegalOperation: Attempted to create a lock file on a read-only directory: /var/lib/mongodb"}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"initandlisten","msg":"Shutting down the MirrorMaestro"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"initandlisten","msg":"Shutting down the WaitForMajorityService"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"initandlisten","msg":"Shutdown: going to close listening sockets"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"initandlisten","msg":"Shutting down the global connection pool"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.333+00:00"},"s":"I",  "c":"STORAGE",  "id":4784906, "ctx":"initandlisten","msg":"Shutting down the FlowControlTicketholder"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"initandlisten","msg":"Stopping further Flow Control ticket acquisitions."}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"initandlisten","msg":"Shutting down the ReplicaSetMonitor"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"initandlisten","msg":"Shutting down the MigrationUtilExecutor"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"CONTROL",  "id":4784925, "ctx":"initandlisten","msg":"Shutting down free monitoring"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"FTDC",     "id":4784926, "ctx":"initandlisten","msg":"Shutting down full-time data capture"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"STORAGE",  "id":4784927, "ctx":"initandlisten","msg":"Shutting down the HealthLog"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"STORAGE",  "id":4784929, "ctx":"initandlisten","msg":"Acquiring the global lock for shutdown"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"initandlisten","msg":"Dropping the scope cache for shutdown"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"initandlisten","msg":"Now exiting"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:31.334+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"initandlisten","msg":"Shutting down","attr":{"exitCode":100}}
mongo_db | ERROR: child process failed, exited with 100
mongo_db | To see additional information in this output, start without the "--fork" option.
mongo_db | about to fork child process, waiting until server is ready for connections.
mongo_db | forked process: 26
mongo_db | 
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.747+00:00"},"s":"W",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****","tags":["startupWarnings"]}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.753+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.762+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.763+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.764+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":26,"port":27017,"dbPath":"/var/lib/mongodb","architecture":"64-bit","host":"d9a0e72377e5"}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.764+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.1","gitVersion":"ad91a93a5a31e175f5cbf8c69561e788bbc55ce1","openSSLVersion":"OpenSSL 1.1.1  11 Sep 2018","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu1804","distarch":"x86_64","target_arch":"x86_64"}}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.764+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"18.04"}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.764+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/tmp/docker-entrypoint-temp-config.json","net":{"bindIp":"127.0.0.1","port":27017,"tls":{"mode":"disabled"}},"processManagement":{"fork":true,"pidFilePath":"/tmp/docker-entrypoint-temp-mongod.pid"},"storage":{"dbPath":"/var/lib/mongodb","journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"path":"/proc/1/fd/1"}}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.768+00:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"IllegalOperation: Attempted to create a lock file on a read-only directory: /var/lib/mongodb"}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.768+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.768+00:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"initandlisten","msg":"Shutting down the MirrorMaestro"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.768+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"initandlisten","msg":"Shutting down the WaitForMajorityService"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.768+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"initandlisten","msg":"Shutdown: going to close listening sockets"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"initandlisten","msg":"Shutting down the global connection pool"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"STORAGE",  "id":4784906, "ctx":"initandlisten","msg":"Shutting down the FlowControlTicketholder"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"initandlisten","msg":"Stopping further Flow Control ticket acquisitions."}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"initandlisten","msg":"Shutting down the ReplicaSetMonitor"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"initandlisten","msg":"Shutting down the MigrationUtilExecutor"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"CONTROL",  "id":4784925, "ctx":"initandlisten","msg":"Shutting down free monitoring"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"FTDC",     "id":4784926, "ctx":"initandlisten","msg":"Shutting down full-time data capture"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"STORAGE",  "id":4784927, "ctx":"initandlisten","msg":"Shutting down the HealthLog"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"STORAGE",  "id":4784929, "ctx":"initandlisten","msg":"Acquiring the global lock for shutdown"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"initandlisten","msg":"Dropping the scope cache for shutdown"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"initandlisten","msg":"Now exiting"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:33.769+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"initandlisten","msg":"Shutting down","attr":{"exitCode":100}}
mongo_db | ERROR: child process failed, exited with 100
mongo_db | To see additional information in this output, start without the "--fork" option.
mongo_db | about to fork child process, waiting until server is ready for connections.
mongo_db | forked process: 26
mongo_db | 
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.898+00:00"},"s":"W",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****","tags":["startupWarnings"]}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.904+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.915+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.915+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.919+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":26,"port":27017,"dbPath":"/var/lib/mongodb","architecture":"64-bit","host":"d9a0e72377e5"}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.919+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.1","gitVersion":"ad91a93a5a31e175f5cbf8c69561e788bbc55ce1","openSSLVersion":"OpenSSL 1.1.1  11 Sep 2018","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu1804","distarch":"x86_64","target_arch":"x86_64"}}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.919+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"18.04"}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.919+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/tmp/docker-entrypoint-temp-config.json","net":{"bindIp":"127.0.0.1","port":27017,"tls":{"mode":"disabled"}},"processManagement":{"fork":true,"pidFilePath":"/tmp/docker-entrypoint-temp-mongod.pid"},"storage":{"dbPath":"/var/lib/mongodb","journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"path":"/proc/1/fd/1"}}}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.922+00:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"IllegalOperation: Attempted to create a lock file on a read-only directory: /var/lib/mongodb"}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.922+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"initandlisten","msg":"Shutting down the MirrorMaestro"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"SHARDING", "id":4784902, "ctx":"initandlisten","msg":"Shutting down the WaitForMajorityService"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"initandlisten","msg":"Shutdown: going to close listening sockets"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"NETWORK",  "id":4784905, "ctx":"initandlisten","msg":"Shutting down the global connection pool"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"STORAGE",  "id":4784906, "ctx":"initandlisten","msg":"Shutting down the FlowControlTicketholder"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"initandlisten","msg":"Stopping further Flow Control ticket acquisitions."}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"initandlisten","msg":"Shutting down the ReplicaSetMonitor"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"SHARDING", "id":4784921, "ctx":"initandlisten","msg":"Shutting down the MigrationUtilExecutor"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"CONTROL",  "id":4784925, "ctx":"initandlisten","msg":"Shutting down free monitoring"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"FTDC",     "id":4784926, "ctx":"initandlisten","msg":"Shutting down full-time data capture"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"STORAGE",  "id":4784927, "ctx":"initandlisten","msg":"Shutting down the HealthLog"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"STORAGE",  "id":4784929, "ctx":"initandlisten","msg":"Acquiring the global lock for shutdown"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.923+00:00"},"s":"I",  "c":"-",        "id":4784931, "ctx":"initandlisten","msg":"Dropping the scope cache for shutdown"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.924+00:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"initandlisten","msg":"Now exiting"}
mongo_db | {"t":{"$date":"2020-11-06T16:51:35.924+00:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"initandlisten","msg":"Shutting down","attr":{"exitCode":100}}
mongo_db | ERROR: child process failed, exited with 100
mongo_db | To see additional information in this output, start without the "--fork" option.
```

**Comment by michaelKurowski** [comment]
Whole mongo output:
https://pastebin.com/PF0RsLi9

**Review by michaelKurowski — CHANGES_REQUESTED** [review]
Please fix mentioned issues

**Comment by Jordan141** [comment]
I believe the errors have been corrected. Remnant logs are a result of pairing a folder to Docker that is on a NTFS file system, but do not seem to affect functionality at this time.

**Review by michaelKurowski — APPROVED** [review]
Good job

**Pull request merged**
