### PR TITLE
Social Media

### LINKED ISSUE #155: Social media doesn't work
/edit-profile/:id
image

/authors/:id
image

### PR DESCRIPTION
**Pull request by Jordan141**
fixes #155 

Social Media includes GitHub, LinkedIn and CodePen

- [x] Extend User Schema
- [x] Add inputs to edit profile
- [x] Show social media on author profile
- [x] Make sure it links properly

### CODE REVIEW

**Comment by Jordan141** [comment]
Ready for review, might need some styling changes for the placeholder

**Comment by michaelKurowski** [comment]
The code looks fine, I'll check how does it look visually and whether it requires additional styling and then eventually merge it

**Comment by michaelKurowski** [comment]
I'll merge it after styling

**Comment by michaelKurowski** [comment]
image
Social medias on author's profile are visible even if He has not set them.

**Review by michaelKurowski — APPROVED** [review]

**Pull request merged**
