### PR TITLE
58 (subtask) categories listing

### PR DESCRIPTION
**Pull request by michaelKurowski**
Pages done in this PR:
- categories listing
- authors
- author profile

### CODE REVIEW

**Comment by michaelKurowski** [comment]
Asuggestion from Marcin:
Increase spacing between articles in listing and make buttons fatter.

**Review by Jordan141 — CHANGES_REQUESTED** [review]
Categories list is good, authors page is good too.

I would make this part tighter and probably smaller in author profile
image

**Comment by michaelKurowski** [comment]
@Jordan141 check now

**Comment by michaelKurowski** [comment]
@Jordan141 Added article edit as well

**Comment by michaelKurowski** [comment]
Added edit profile

**Comment by michaelKurowski** [comment]
Added login and register

**Comment by Jordan141** [comment]
- [x] Category
- [x]  Authors
- [x]  Authors Profile
- [x] Edit Article
- [ ]  Edit Profile

Edit profile needs an input for profile page description (this will be dependent on their role type if it appears).
Profile picture change will be by clicking on the picture.

After that change you can merge.

**Comment by Jordan141** [comment]
Login and Register layouts need to include captcha area.

**Comment by michaelKurowski** [comment]
Error page added

**Review by Jordan141 — APPROVED** [review]

**Pull request merged**
