### PR TITLE
246 fix permissions issue with mongo container

### LINKED ISSUE #246: Fix ./db permissions
Fix `./db` permissions, so that docker will have access to it without sudo.

### PR DESCRIPTION
**Pull request by michaelKurowski**
fixes #246

### CODE REVIEW

**Comment by michaelKurowski** [comment]
@Jordan141 let me know whether it's an acceptable solution

**Comment by michaelKurowski** [comment]
From Matt
> won't DB data be deleted along with container if there is no volume attached?
> there is --volumes option for docker rm, maybe it needs to be provided

**Comment by michaelKurowski** [comment]
TODO: Check whether I can create volume without mapping it

**Comment by michaelKurowski** [comment]
```
Removing network articleblog_default
HEAD is now at abd372e Merge pull request #257 from Jordan141/gitignore-exception-dummy-images
Creating network "articleblog_default" with the default driver
Building web
[250845] Failed to execute script docker-compose
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 346, in ensure_image_exists
  File "compose/service.py", line 1125, in build
  File "docker/api/build.py", line 160, in build
  File "docker/utils/build.py", line 30, in tar
  File "docker/utils/build.py", line 49, in exclude_paths
  File "docker/utils/build.py", line 214, in rec_walk
  File "docker/utils/build.py", line 214, in rec_walk
  File "docker/utils/build.py", line 184, in rec_walk
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/www/articleblog/db/diagnostic.data'
```
This PR might fix autodeploy, as this is the latest log.

**Review by Jordan141 — APPROVED** [review]

**Pull request merged**
