### PR TITLE
58 (subtask) desktop article view

### LINKED ISSUE #58: Prepare HTMl/CSS templates for layout
Desktop:
 - [x] articles view
 - [x] articles listing / homepage
 - [x] categories listing
 - [x] authors
 - [x] author profile
 - [ ] edit profile
 - [x] add/edit article
- [x] register
- [x] login
- [x] error page

Mobile:
 - [ ] articles view
 - [ ] articles listing / homepage
 - [ ] categories listing
 - [ ] authors
 - [ ] author profile
 - [ ] edit profile
- [ ] register
- [ ] login
- [ ] error page

Other:
 - [ ] Notification system
 - [ ] Modal system
 - [ ] Final refactor

### PR DESCRIPTION
**Pull request by michaelKurowski**

### CODE REVIEW

**Comment by michaelKurowski** [comment]
I've attached readme how to run the template

**Review by Jordan141 — CHANGES_REQUESTED** [review]
Looks good, only change that needs done is all CSS/JS must be in .css/.js files in accordance with the content security policy.

**Comment by michaelKurowski** [comment]
It's only for design easiness of development.
All css files can be merged into one when moving onto ejs.

**Comment by michaelKurowski** [comment]
I'll make a script at the end that will merge all CSS from these files into one .css file

**Comment by michaelKurowski** [comment]
How exactly CSS styles being not in .css files is a security vulnerability?

**Comment by michaelKurowski** [comment]
Actually maybe I'll move it to ejs, just without writing JS.

**Review by Jordan141 — APPROVED** [review]

**Pull request merged**
