### PR TITLE
Migrate HTML Designs to EJS

### LINKED ISSUE #90: Display dates in user's timezone
Dates should be displayed as follow:
 - hh:mm for the dates of the same day
 - "Yesterday" for previous day
 - dd monthName yyyy for older dates
 - Time should be displayed in user's timezone, I suggest a script on frontend that will handle that

### PR DESCRIPTION
**Pull request by Jordan141**
Converted to EJS:
- [x] articles view
- [x] articles listing / homepage
- [x] categories listing
- [x] authors
- [x] author profile
- [x] edit profile
- [x] register
- [x] login
- [x] error page
- [x] header
- [x] footer

Connected to backend routes
- [x] articles view
- [x] articles listing / homepage
- [x] categories listing
- [x] authors
- [x] author profile
- [x] edit profile
- [x] comments
- [x] comment section
- [x] register
- [x] login
- [x] error page
- [x] header
- [x] footer

Misc. pages to re-add to the application:
- [x] Approval listing
- [x] Approve page
- [x] Register
- [x] New/Edit article

Closes a whole bunch of issues, someone write them down below so I can edit this 
TODO: add "create new article button" for authors, add "register" button to homepage,  creation date to article model, logout button

resolves #90 #69 #68 #70 #58 #46 #45 #44 #43 #87 #53 #51 #50 #48 #47

### CODE REVIEW

**Comment by Jordan141** [comment]
page-title and page-content setup will have to change to adjust it to EJS, converting raw html to ejs templates first.

**Comment by michaelKurowski** [comment]
- [ ] Images on article listing should redirect used to said article
 - [ ] The big article in article listing should be the first article on the list from the backend, while the smaller ones are following ones
 - [ ] Profile icon in the header, once logged in, should redirect to edit user's profile page.

**Comment by michaelKurowski** [comment]
- [ ] After uploading a photo for my profile, the server crashed
- [ ] Bio doesn't show on authors listing

**Comment by michaelKurowski** [comment]
FYI:
I've fixed issue with edit icon not working on articles on my branch. The logo was covering the icon with invisible block.

**Comment by Jordan141** [comment]
### Bug:
#### Edit profile avatar icon:
- We must use styling to fix the current bug, this is the only method that the CSP will allow us to use to dynamically replace an image that is dependent on a dynamic URL

**Comment by Jordan141** [comment]
Current list of objectives:
- [ ] Clicking Hamburger Icon should open menu
- [ ] Page title should be the same as in page's header, but with Pinch of Code - prefix i.e. "Pich of Code - Latest articles"
- [ ] Dates should be displayed as above
- [ ] Have Michael check if the bug still persists
- [ ] MyAccount icon should have color --color-secondary for logged in user
- [ ] Link up Author Panel
- [ ] Link up the righthand panel thing

**Comment by michaelKurowski** [comment]
- [ ] Dates on comments are NaN instead of timestamps. Both for the comments loaded from your db, and the ones I create.
image

**Comment by michaelKurowski** [comment]
- [ ] for me - hamburger menu

**Pull request merged**
